In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [19]:
# Load the CSV file into a DataFrame (replace 'data.csv' with your file path)
df = pd.read_excel('/Users/pablo/Desktop/G20_Project/cadre_harmonise_caf_ipc.xlsx')

In [20]:
# Display the first few rows to get an idea of the dataset
print("First 5 rows of the dataset:")
print(df.head())

First 5 rows of the dataset:
      adm0_name adm0_pcod2 adm0_pcod3 adm0_5_name  adm0_5_pcod2  \
0  Burkina Faso         BF        BFA         NaN           NaN
1  Burkina Faso         BF        BFA         NaN           NaN
2  Burkina Faso         BF        BFA         NaN           NaN
3  Burkina Faso         BF        BFA         NaN           NaN
4  Burkina Faso         BF        BFA         NaN           NaN

         adm1_name adm1_pcod2 adm1_5_name adm1_5_pcod2   adm2_name  ...  \
0           Centre       BF13         NaN          NaN     Kadiogo  ...
1  Plateau Central       BF55         NaN          NaN  Ganzourgou  ...
2  Plateau Central       BF55         NaN          NaN  Oubritenga  ...
3  Plateau Central       BF55         NaN          NaN   Kourweogo  ...
4       Centre-Sud       BF51         NaN          NaN      Bazega  ...

  LhHCSCat_StressStrategies LhHCSCat_CrisisStategies  \
0                       NaN                      NaN
1                       NaN                      NaN
2                       NaN                      NaN
3                       NaN                      NaN
4                       NaN                      NaN

  LhHCSCat_EmergencyStrategies LhHCSCat_finalphase rCSI_Phase1  rCSI_Phase2  \
0                          NaN                 NaN         NaN          NaN
1                          NaN                 NaN         NaN          NaN
2                          NaN                 NaN         NaN          NaN
3                          NaN                 NaN         NaN          NaN
4                          NaN                 NaN         NaN          NaN

  rCSI_Phase3  rCSI_finalphase notes  usethisperiod
0         NaN              NaN   NaN              Y
1         NaN              NaN   NaN              Y
2         NaN              NaN   NaN              Y
3         NaN              NaN   NaN              Y
4         NaN              NaN   NaN              Y

[5 rows x 61 columns]

In [21]:
# Get a summary of the DataFrame including data types and non-null counts
print("\nDataFrame Info:")
print(df.info())

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35744 entries, 0 to 35743
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   adm0_name                     35744 non-null  object
 1   adm0_pcod2                    35726 non-null  object
 2   adm0_pcod3                    35744 non-null  object
 3   adm0_5_name                   594 non-null    object
 4   adm0_5_pcod2                  0 non-null      float64
 5   adm1_name                     35727 non-null  object
 6   adm1_pcod2                    35727 non-null  object
 7   adm1_5_name                   8686 non-null   object
 8   adm1_5_pcod2                  8322 non-null   object
 9   adm2_name                     32623 non-null  object
 10  adm2_pcod2                    32547 non-null  object
 11  adm2_5_name                   751 non-null    object
 12  adm2_5_pcod2                  712 non-null    object
 13  adm3_name                     373 non-null    object
 14  adm3_pcod2                    349 non-null    object
 15  exercise_code                 35744 non-null  int64
 16  exercise_label                35744 non-null  object
 17  exercise_year                 35744 non-null  int64
 18  chtype                        35744 non-null  object
 19  reference_code                35744 non-null  int64
 20  reference_label               35744 non-null  object
 21  reference_year                35744 non-null  int64
 22  population                    35742 non-null  float64
 23  phase_class                   35437 non-null  float64
 24  phase1                        35687 non-null  float64
 25  phase2                        35687 non-null  float64
 26  phase3                        35493 non-null  float64
 27  phase4                        35324 non-null  float64
 28  phase5                        35117 non-null  float64
 29  phase35                       35496 non-null  float64
 30  foodconsumption_phase         8532 non-null   float64
 31  livelihoods_phase             8204 non-null   float64
 32  nutrition_phase               4042 non-null   float64
 33  mortality_phase               1428 non-null   float64
 34  FCG_Poor                      3467 non-null   float64
 35  FCG_Borderline                3507 non-null   float64
 36  FCG_Acceptable                3511 non-null   float64
 37  FCG_finalphase                3200 non-null   float64
 38  HDDS_Phase1                   2801 non-null   float64
 39  HDDS_Phase2                   2793 non-null   float64
 40  HDDS_Phase3                   2781 non-null   float64
 41  HDDS_Phase4                   2751 non-null   float64
 42  HDDS_Phase5                   2728 non-null   float64
 43  HDDS_finalphase               2489 non-null   float64
 44  HHS_Phase1                    2371 non-null   float64
 45  HHS_Phase2                    2370 non-null   float64
 46  HHS_Phase3                    2371 non-null   float64
 47  HHS_Phase4                    2366 non-null   float64
 48  HHS_Phase5                    2357 non-null   float64
 49  HHS_finalphase                2084 non-null   float64
 50  LhHCSCat_NoStrategies         3483 non-null   float64
 51  LhHCSCat_StressStrategies     3483 non-null   float64
 52  LhHCSCat_CrisisStategies      3470 non-null   float64
 53  LhHCSCat_EmergencyStrategies  3461 non-null   float64
 54  LhHCSCat_finalphase           3170 non-null   float64
 55  rCSI_Phase1                   3512 non-null   float64
 56  rCSI_Phase2                   3510 non-null   float64
 57  rCSI_Phase3                   3489 non-null   float64
 58  rCSI_finalphase               3188 non-null   float64
 59  notes                         229 non-null    object
 60  usethisperiod                 35744 non-null  object
dtypes: float64(38), int64(4), object(19)
memory usage: 16.6+ MB
None

In [22]:
# Check for missing values in each column
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
adm0_name              0
adm0_pcod2            18
adm0_pcod3             0
adm0_5_name        35150
adm0_5_pcod2       35744
                   ...
rCSI_Phase2        32234
rCSI_Phase3        32255
rCSI_finalphase    32556
notes              35515
usethisperiod          0
Length: 61, dtype: int64

In [32]:
cols_to_keep = [
    'adm0_name', 'adm1_name', 'adm2_name', 'chtype',
    'reference_label', 'reference_year',
    'population', 'phase_class', 'phase1', 'phase2', 'phase3',
    'phase4', 'phase5', 'phase35', 'usethisperiod', 'foodconsumption_phase',
    'livelihoods_phase','nutrition_phase', 'mortality_phase'
]
df = df[cols_to_keep]

In [33]:
# Filter rows where column 'X' equals 'MRT'
filtered_df = df[df['adm1_name'] == 'Assaba']

filtered_df = filtered_df[filtered_df['usethisperiod']=='Y']

#filtered_df = filtered_df[filtered_df['chtype']=='projected']

In [34]:
filtered_df = filtered_df.drop('usethisperiod', axis=1)
filtered_df = filtered_df.drop('phase_class', axis=1)
filtered_df = filtered_df.drop('phase5', axis=1)
filtered_df = filtered_df.drop('mortality_phase', axis=1)

In [35]:
print(filtered_df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 83 entries, 115 to 35032
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adm0_name              83 non-null     object
 1   adm1_name              83 non-null     object
 2   adm2_name              63 non-null     object
 3   chtype                 83 non-null     object
 4   reference_label        83 non-null     object
 5   reference_year         83 non-null     int64
 6   population             83 non-null     float64
 7   phase1                 83 non-null     float64
 8   phase2                 83 non-null     float64
 9   phase3                 83 non-null     float64
 10  phase4                 82 non-null     float64
 11  phase35                83 non-null     float64
 12  foodconsumption_phase  36 non-null     float64
 13  livelihoods_phase      36 non-null     float64
 14  nutrition_phase        36 non-null     float64
dtypes: float64(9), int64(1), object(5)
memory usage: 10.4+ KB
None

In [36]:
filtered_df['adm2_name'] = filtered_df['adm2_name'].fillna('unknown')

In [37]:
filtered_df

,adm0_name,adm1_name,adm2_name,chtype,reference_label,reference_year,population,phase1,phase2,phase3,phase4,phase35,foodconsumption_phase,livelihoods_phase,nutrition_phase
115,Mauritania,Assaba,unknown,current,Jan-May,2014,323761.0,262246.0,61515.0,0.0,0.0,0.0,NaN,NaN,NaN
346,Mauritania,Assaba,unknown,projected,Jun-Aug,2014,323761.0,226633.0,55039.0,32376.0,9713.0,42089.0,NaN,NaN,NaN
623,Mauritania,Assaba,unknown,current,Sep-Dec,2014,333686.0,223570.0,83422.0,26695.0,0.0,26695.0,NaN,NaN,NaN
1063,Mauritania,Assaba,unknown,current,Jan-May,2015,343733.0,230301.0,82496.0,30936.0,NaN,30936.0,NaN,NaN,NaN
1453,Mauritania,Assaba,unknown,projected,Jun-Aug,2015,343733.0,171866.0,96245.0,72184.0,3437.0,75621.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31763,Mauritania,Assaba,Kankossa,current,Jan-May,2024,107577.0,61319.0,32273.0,13985.0,0.0,13985.0,NaN,NaN,NaN
31764,Mauritania,Assaba,Kiffa,projected,Jun-Aug,2024,144376.0,59194.0,50532.0,30319.0,4331.0,34650.0,NaN,NaN,NaN
31765,Mauritania,Assaba,Kiffa,current,Jan-May,2024,144376.0,89513.0,36094.0,18769.0,0.0,18769.0,NaN,NaN,NaN
35017,Mauritania,Assaba,unknown,current,Sep-Dec,2024,451804.0,374997.0,67771.0,9036.0,0.0,9036.0,NaN,NaN,NaN
35032,Mauritania,Assaba,unknown,projected,Jun-Aug,2025,451804.0,334335.0,99397.0,18072.0,0.0,18072.0,NaN,NaN,NaN

In [38]:
import pandas as pd
import numpy as np

# Define a function to compute the mean excluding zeros and NaNs
def mean_excluding_zeros(series):
    filtered = series[(series != 0) & (~series.isna())]
    return filtered.mean()

# Define a function to compute the mode (most frequent value)
def mode_value(series):
    # Drop NaN values first
    series = series.dropna()
    if series.empty:
        return np.nan
    # Return the first mode (in case of multiple modes)
    mode_series = series.mode()
    return mode_series.iloc[0] if not mode_series.empty else np.nan

# Define the aggregation dictionary
agg_dict = {
    "adm0_name": "first",
    "adm1_name": "first",
    "chtype": "first",
    "reference_label": "first",
    "population": mean_excluding_zeros,
    "phase1": mean_excluding_zeros,
    "phase2": mean_excluding_zeros,
    "phase3": mean_excluding_zeros,
    "phase4": mean_excluding_zeros,
    "phase35": mean_excluding_zeros,
    "foodconsumption_phase": mode_value,
    "livelihoods_phase": mode_value,
    "nutrition_phase": mode_value
}

# Group by the year and aggregate accordingly
# Group by both reference_year and adm1_name
grouped_df = filtered_df.groupby(["reference_year", "adm2_name"]).agg(agg_dict).reset_index()


print(grouped_df)

    reference_year adm2_name   adm0_name adm1_name     chtype reference_label  \
0             2014   unknown  Mauritania    Assaba    current         Jan-May
1             2015   unknown  Mauritania    Assaba    current         Jan-May
2             2016   unknown  Mauritania    Assaba    current         Jan-May
3             2017   unknown  Mauritania    Assaba    current         Jan-May
4             2018   unknown  Mauritania    Assaba    current         Jan-May
5             2019   Barkeol  Mauritania    Assaba    current         Sep-Dec
6             2019  Boumdeid  Mauritania    Assaba    current         Sep-Dec
7             2019   Guerrou  Mauritania    Assaba    current         Sep-Dec
8             2019  Kankossa  Mauritania    Assaba    current         Sep-Dec
9             2019     Kiffa  Mauritania    Assaba    current         Sep-Dec
10            2019   unknown  Mauritania    Assaba    current         Jan-May
11            2020   Barkeol  Mauritania    Assaba  projected         Jun-Aug
12            2020  Boumdeid  Mauritania    Assaba  projected         Jun-Aug
13            2020   Guerrou  Mauritania    Assaba  projected         Jun-Aug
14            2020  Kankossa  Mauritania    Assaba  projected         Jun-Aug
15            2020     Kiffa  Mauritania    Assaba  projected         Jun-Aug
16            2021   Barkeol  Mauritania    Assaba    current         Jan-May
17            2021  Boumdeid  Mauritania    Assaba    current         Jan-May
18            2021   Guerrou  Mauritania    Assaba    current         Jan-May
19            2021  Kankossa  Mauritania    Assaba    current         Jan-May
20            2021     Kiffa  Mauritania    Assaba    current         Jan-May
21            2022   Barkeol  Mauritania    Assaba    current         Jan-May
22            2022  Boumdeid  Mauritania    Assaba    current         Jan-May
23            2022   Guerrou  Mauritania    Assaba    current         Jan-May
24            2022  Kankossa  Mauritania    Assaba    current         Jan-May
25            2022     Kiffa  Mauritania    Assaba    current         Jan-May
26            2022   unknown  Mauritania    Assaba    current         Sep-Dec
27            2023   Barkeol  Mauritania    Assaba    current         Jan-May
28            2023  Boumdeid  Mauritania    Assaba    current         Jan-May
29            2023   Guerrou  Mauritania    Assaba    current         Jan-May
30            2023  Kankossa  Mauritania    Assaba    current         Jan-May
31            2023     Kiffa  Mauritania    Assaba    current         Jan-May
32            2024   Barkeol  Mauritania    Assaba  projected         Jun-Aug
33            2024  Boumdeid  Mauritania    Assaba  projected         Jun-Aug
34            2024   Guerrou  Mauritania    Assaba    current         Jan-May
35            2024  Kankossa  Mauritania    Assaba  projected         Jun-Aug
36            2024     Kiffa  Mauritania    Assaba  projected         Jun-Aug
37            2024   unknown  Mauritania    Assaba    current         Sep-Dec
38            2025   unknown  Mauritania    Assaba  projected         Jun-Aug

       population         phase1         phase2        phase3   phase4  \
0   327069.333333  237483.000000   66658.666667  29535.500000   9713.0
1   343042.333333  221748.666667   80080.000000  40067.666667   3437.0
2   349827.000000  279861.666667   55972.333333  13993.333333      NaN
3   360249.000000  252174.333333   67246.666667  37225.666667  10807.0
4   371778.000000  219584.333333   95403.666667  55561.000000   3688.0
5    94807.000000   71105.000000   14221.000000   7585.000000   1896.0
6     9394.000000    7327.000000    1503.000000    564.000000      NaN
7    53240.000000   37801.000000    7986.000000   6389.000000   1065.0
8    97884.000000   71456.000000   14683.000000   9788.000000   1958.0
9   131368.000000   98526.000000   19705.000000  10509.000000   2627.0
10  377656.000000  183163.500000  118961.500000  69866.000000   5665.0
11   94807.000000   65417.000000   17065.000000  10428.500000   3792.0
12    9394.000000    6951.500000    1550.000000    845.500000     94.0
13   53240.000000   38599.000000    7453.500000   5058.000000   4259.0
14   97884.000000   70966.000000   15661.500000   7341.500000   7831.0
15  131368.000000   93928.000000   21675.500000  13136.500000   5255.0
16   97844.000000   62635.666667   25416.333333   9145.000000   1941.0
17    9694.666667    6300.000000    2649.666667    745.333333      NaN
18   54946.333333   33880.666667   15025.666667   5857.666667    545.0
19  101020.333333   68749.666667   24547.000000   7723.666667      NaN
20  135576.333333   87142.000000   37107.333333  11326.333333      NaN
21   99390.256700   40253.000000   33792.500000  21866.000000   3479.0
22    9848.095297    4727.000000    2905.000000   1920.500000    295.5
23   55814.580770   29024.000000   16186.500000   9767.500000    837.0
24  102616.978800   44638.500000   35916.000000  19497.500000   2565.5
25  137719.088400   60596.500000   46824.500000  28232.000000   4132.0
26  405389.000000  287826.000000   93239.000000  20269.000000   4054.0
27  102576.333333   62587.666667   24287.333333  15701.333333      NaN
28   10164.000000    7312.666667    2104.000000    747.333333      NaN
29   57603.666667   38671.666667   11489.000000   7442.666667      NaN
30  105906.333333   74593.333333   16895.000000  14418.000000      NaN
31  142133.333333  112319.000000   23178.000000   6636.666667      NaN
32  104195.000000   50014.000000   32300.000000  21881.000000      NaN
33   10324.000000    5678.000000    1858.000000   2581.000000    206.0
34   58513.000000   38618.500000   11702.500000   8191.500000      NaN
35  107577.000000   52175.000000   34962.500000  18826.000000   3227.0
36  144376.000000   74353.500000   43313.000000  24544.000000   4331.0
37  451804.000000  374997.000000   67771.000000   9036.000000      NaN
38  451804.000000  334335.000000   99397.000000  18072.000000      NaN

         phase35  foodconsumption_phase  livelihoods_phase  nutrition_phase
0   34392.000000                    NaN                NaN              NaN
1   41213.333333                    NaN                NaN              NaN
2   13993.333333                    NaN                NaN              NaN
3   40828.000000                    NaN                NaN              NaN
4   56790.333333                    NaN                NaN              NaN
5    9481.000000                    NaN                NaN              NaN
6     564.000000                    NaN                NaN              NaN
7    7454.000000                    NaN                NaN              NaN
8   11746.000000                    NaN                NaN              NaN
9   13137.000000                    NaN                NaN              NaN
10  75531.000000                    NaN                NaN              NaN
11  12324.500000                    NaN                NaN              NaN
12    892.500000                    NaN                NaN              NaN
13   7187.500000                    NaN                NaN              NaN
14  11257.000000                    NaN                NaN              NaN
15  15764.000000                    NaN                NaN              NaN
16   9792.000000                    1.0                2.0              2.0
17    745.333333                    1.0                2.0              4.0
18   6039.666667                    1.0                2.0              4.0
19   7723.666667                    1.0                2.0              2.0
20  11326.333333                    1.0                2.0              4.0
21  25345.000000                    2.0                3.0              4.0
22   2216.000000                    2.0                3.0              4.0
23  10604.500000                    2.0                3.0              4.0
24  22063.000000                    2.0                3.0              4.0
25  30298.000000                    2.0                3.0              3.0
26  24323.000000                    1.0                2.0              3.0
27  15701.333333                    2.0                1.0              2.0
28    747.333333                    1.0                1.0              2.0
29   7442.666667                    2.0                1.0              2.0
30  14418.000000                    2.0                1.0              2.0
31   6636.666667                    1.0                1.0              2.0
32  21881.000000                    NaN                NaN              NaN
33   2787.000000                    NaN                NaN              NaN
34   8191.500000                    NaN                NaN              NaN
35  20439.500000                    NaN                NaN              NaN
36  26709.500000                    NaN                NaN              NaN
37   9036.000000                    NaN                NaN              NaN
38  18072.000000                    NaN                NaN              NaN

In [39]:
grouped_df=grouped_df.drop("reference_label",axis=1)

In [40]:
grouped_df

,reference_year,adm2_name,adm0_name,adm1_name,chtype,population,phase1,phase2,phase3,phase4,phase35,foodconsumption_phase,livelihoods_phase,nutrition_phase
0,2014,unknown,Mauritania,Assaba,current,327069.333333,237483.000000,66658.666667,29535.500000,9713.0,34392.000000,NaN,NaN,NaN
1,2015,unknown,Mauritania,Assaba,current,343042.333333,221748.666667,80080.000000,40067.666667,3437.0,41213.333333,NaN,NaN,NaN
2,2016,unknown,Mauritania,Assaba,current,349827.000000,279861.666667,55972.333333,13993.333333,NaN,13993.333333,NaN,NaN,NaN
3,2017,unknown,Mauritania,Assaba,current,360249.000000,252174.333333,67246.666667,37225.666667,10807.0,40828.000000,NaN,NaN,NaN
4,2018,unknown,Mauritania,Assaba,current,371778.000000,219584.333333,95403.666667,55561.000000,3688.0,56790.333333,NaN,NaN,NaN
5,2019,Barkeol,Mauritania,Assaba,current,94807.000000,71105.000000,14221.000000,7585.000000,1896.0,9481.000000,NaN,NaN,NaN
6,2019,Boumdeid,Mauritania,Assaba,current,9394.000000,7327.000000,1503.000000,564.000000,NaN,564.000000,NaN,NaN,NaN
7,2019,Guerrou,Mauritania,Assaba,current,53240.000000,37801.000000,7986.000000,6389.000000,1065.0,7454.000000,NaN,NaN,NaN
8,2019,Kankossa,Mauritania,Assaba,current,97884.000000,71456.000000,14683.000000,9788.000000,1958.0,11746.000000,NaN,NaN,NaN
9,2019,Kiffa,Mauritania,Assaba,current,131368.000000,98526.000000,19705.000000,10509.000000,2627.0,13137.000000,NaN,NaN,NaN
10,2019,unknown,Mauritania,Assaba,current,377656.000000,183163.500000,118961.500000,69866.000000,5665.0,75531.000000,NaN,NaN,NaN
11,2020,Barkeol,Mauritania,Assaba,projected,94807.000000,65417.000000,17065.000000,10428.500000,3792.0,12324.500000,NaN,NaN,NaN
12,2020,Boumdeid,Mauritania,Assaba,projected,9394.000000,6951.500000,1550.000000,845.500000,94.0,892.500000,NaN,NaN,NaN
13,2020,Guerrou,Mauritania,Assaba,projected,53240.000000,38599.000000,7453.500000,5058.000000,4259.0,7187.500000,NaN,NaN,NaN
14,2020,Kankossa,Mauritania,Assaba,projected,97884.000000,70966.000000,15661.500000,7341.500000,7831.0,11257.000000,NaN,NaN,NaN
15,2020,Kiffa,Mauritania,Assaba,projected,131368.000000,93928.000000,21675.500000,13136.500000,5255.0,15764.000000,NaN,NaN,NaN
16,2021,Barkeol,Mauritania,Assaba,current,97844.000000,62635.666667,25416.333333,9145.000000,1941.0,9792.000000,1.0,2.0,2.0
17,2021,Boumdeid,Mauritania,Assaba,current,9694.666667,6300.000000,2649.666667,745.333333,NaN,745.333333,1.0,2.0,4.0
18,2021,Guerrou,Mauritania,Assaba,current,54946.333333,33880.666667,15025.666667,5857.666667,545.0,6039.666667,1.0,2.0,4.0
19,2021,Kankossa,Mauritania,Assaba,current,101020.333333,68749.666667,24547.000000,7723.666667,NaN,7723.666667,1.0,2.0,2.0
20,2021,Kiffa,Mauritania,Assaba,current,135576.333333,87142.000000,37107.333333,11326.333333,NaN,11326.333333,1.0,2.0,4.0
21,2022,Barkeol,Mauritania,Assaba,current,99390.256700,40253.000000,33792.500000,21866.000000,3479.0,25345.000000,2.0,3.0,4.0
22,2022,Boumdeid,Mauritania,Assaba,current,9848.095297,4727.000000,2905.000000,1920.500000,295.5,2216.000000,2.0,3.0,4.0
23,2022,Guerrou,Mauritania,Assaba,current,55814.580770,29024.000000,16186.500000,9767.500000,837.0,10604.500000,2.0,3.0,4.0
24,2022,Kankossa,Mauritania,Assaba,current,102616.978800,44638.500000,35916.000000,19497.500000,2565.5,22063.000000,2.0,3.0,4.0
25,2022,Kiffa,Mauritania,Assaba,current,137719.088400,60596.500000,46824.500000,28232.000000,4132.0,30298.000000,2.0,3.0,3.0
26,2022,unknown,Mauritania,Assaba,current,405389.000000,287826.000000,93239.000000,20269.000000,4054.0,24323.000000,1.0,2.0,3.0
27,2023,Barkeol,Mauritania,Assaba,current,102576.333333,62587.666667,24287.333333,15701.333333,NaN,15701.333333,2.0,1.0,2.0
28,2023,Boumdeid,Mauritania,Assaba,current,10164.000000,7312.666667,2104.000000,747.333333,NaN,747.333333,1.0,1.0,2.0
29,2023,Guerrou,Mauritania,Assaba,current,57603.666667,38671.666667,11489.000000,7442.666667,NaN,7442.666667,2.0,1.0,2.0
30,2023,Kankossa,Mauritania,Assaba,current,105906.333333,74593.333333,16895.000000,14418.000000,NaN,14418.000000,2.0,1.0,2.0
31,2023,Kiffa,Mauritania,Assaba,current,142133.333333,112319.000000,23178.000000,6636.666667,NaN,6636.666667,1.0,1.0,2.0
32,2024,Barkeol,Mauritania,Assaba,projected,104195.000000,50014.000000,32300.000000,21881.000000,NaN,21881.000000,NaN,NaN,NaN
33,2024,Boumdeid,Mauritania,Assaba,projected,10324.000000,5678.000000,1858.000000,2581.000000,206.0,2787.000000,NaN,NaN,NaN
34,2024,Guerrou,Mauritania,Assaba,current,58513.000000,38618.500000,11702.500000,8191.500000,NaN,8191.500000,NaN,NaN,NaN
35,2024,Kankossa,Mauritania,Assaba,projected,107577.000000,52175.000000,34962.500000,18826.000000,3227.0,20439.500000,NaN,NaN,NaN
36,2024,Kiffa,Mauritania,Assaba,projected,144376.000000,74353.500000,43313.000000,24544.000000,4331.0,26709.500000,NaN,NaN,NaN
37,2024,unknown,Mauritania,Assaba,current,451804.000000,374997.000000,67771.000000,9036.000000,NaN,9036.000000,NaN,NaN,NaN
38,2025,unknown,Mauritania,Assaba,projected,451804.000000,334335.000000,99397.000000,18072.000000,NaN,18072.000000,NaN,NaN,NaN

In [41]:
grouped_df.to_csv("cadre_harmonise_caf_ipc_assaba_yearly_grouped.csv")

In [43]:
filtered_df['reference_label'].unique()

array(['Jan-May', 'Jun-Aug', 'Sep-Dec'], dtype=object)